# Generated by Django 3.0 on 2021-02-27 19:23

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('token_pool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenpool',
            name='expire_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 27, 19, 24, 25, 564435)),
        ),
        migrations.AlterField(
            model_name='tokenpool',
            name='token',
            field=models.CharField(default=uuid.UUID('58131a5b-96e3-45c4-921c-358d6dce6b5e'), max_length=200, verbose_name='token'),
        ),
    ]
