# Generated by Django 3.0 on 2021-02-28 07:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('token_pool', '0004_auto_20210227_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenpool',
            name='token',
            field=models.CharField(default=uuid.UUID('d48dd5f0-c8d5-43b7-ae60-ff80d4c3d274'), max_length=200, unique=True, verbose_name='token'),
        ),
    ]
