# Generated by Django 3.0 on 2021-02-28 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_pool', '0005_auto_20210228_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenpool',
            name='token',
            field=models.CharField(max_length=200, unique=True, verbose_name='token'),
        ),
    ]
